name: sttkit
channels:
  - defaults
dependencies:
  - bioconductor-annotationdbi
  - bioconductor-batchelor
  - bioconductor-bayesspace
  - bioconductor-beachmat
  - bioconductor-biobase
  - bioconductor-biocfilecache
  - bioconductor-biocgenerics
  - bioconductor-biocio
  - bioconductor-biocneighbors
  - bioconductor-biocparallel
  - bioconductor-biocsingular
  - bioconductor-biomart
  - bioconductor-biostrings
  - bioconductor-bluster
  - bioconductor-bsgenome
  - bioconductor-consensusclusterplus
  - bioconductor-delayedarray
  - bioconductor-delayedmatrixstats
  - bioconductor-dnacopy
  - bioconductor-edger
  - bioconductor-enhancedvolcano
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-infercnv
  - bioconductor-iranges
  - bioconductor-keggrest
  - bioconductor-limma
  - bioconductor-matrixgenerics
  - bioconductor-metapod
  - bioconductor-residualmatrix
  - bioconductor-rhdf5
  - bioconductor-rhdf5filters
  - bioconductor-rhdf5lib
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-scaledmatrix
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-scuttle
  - bioconductor-singlecellexperiment
  - bioconductor-sparsematrixstats
  - bioconductor-summarizedexperiment
  - bioconductor-variantannotation
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - hdf5
  - mpi
  - openmpi
  - r-abind
  - r-ape
  - r-argparse
  - r-ash
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-beeswarm
  - r-bh
  - r-bibtex
  - r-biocmanager
  - r-bit
  - r-bit64
  - r-bitops
  - r-blob
  - r-brew
  - r-brio
  - r-bslib
  - r-cachem
  - r-cairo
  - r-callr
  - r-catools
  - r-cli
  - r-clipr
  - r-cluster
  - r-coda
  - r-codetools
  - r-coin
  - r-colorspace
  - r-commonmark
  - r-corrplot
  - r-covr
  - r-cowplot
  - r-cpp11
  - r-crayon
  - r-credentials
  - r-crosstalk
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-deldir
  - r-desc
  - r-devtools
  - r-diffobj
  - r-digest
  - r-dirichletreg
  - r-doparallel
  - r-dplyr
  - r-dqrng
  - r-dt
  - r-ellipsis
  - r-evaluate
  - r-extrafont
  - r-extrafontdb
  - r-fansi
  - r-farver
  - r-fastcluster
  - r-fastmap
  - r-filelock
  - r-findpython
  - r-fitdistrplus
  - r-fnn
  - r-fontawesome
  - r-foreach
  - r-formatr
  - r-formula
  - r-fs
  - r-futile.logger
  - r-futile.options
  - r-future
  - r-future.apply
  - r-generics
  - r-gert
  - r-getopt
  - r-ggalt
  - r-ggbeeswarm
  - r-ggplot2
  - r-ggrastr
  - r-ggrepel
  - r-ggridges
  - r-gh
  - r-git2r
  - r-gitcreds
  - r-globals
  - r-glue
  - r-goftest
  - r-gplots
  - r-gridbase
  - r-gridextra
  - r-gtable
  - r-gtools
  - r-harmony
  - r-hdf5r
  - r-here
  - r-hexbin
  - r-hiddenmarkov
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httpuv
  - r-httr
  - r-ica
  - r-igraph
  - r-ini
  - r-irlba
  - r-isoband
  - r-iterators
  - r-jquerylib
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-lambda.r
  - r-later
  - r-lattice
  - r-lazyeval
  - r-leiden
  - r-libcoin
  - r-lifecycle
  - r-listenv
  - r-lmtest
  - r-locfit
  - r-lsei
  - r-magrittr
  - r-maps
  - r-markdown
  - r-mass
  - r-matrix
  - r-matrixstats
  - r-maxlik
  - r-mclust
  - r-memoise
  - r-mgcv
  - r-mime
  - r-miniui
  - r-misctools
  - r-modeltools
  - r-multcomp
  - r-munsell
  - r-mvtnorm
  - r-nlme
  - r-nloptr
  - r-nmf
  - r-npsurv
  - r-openssl
  - r-optparse
  - r-parallelly
  - r-patchwork
  - r-pbapply
  - r-pheatmap
  - r-phyclust
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-pkgmaker
  - r-plogr
  - r-plotly
  - r-plyr
  - r-png
  - r-polyclip
  - r-praise
  - r-prettyunits
  - r-processx
  - r-progress
  - r-progressr
  - r-proj4
  - r-promises
  - r-ps
  - r-purrr
  - r-r6
  - r-ragg
  - r-randomforestsrc
  - r-rann
  - r-rappdirs
  - r-rcmdcheck
  - r-rcolorbrewer
  - r-rcpp
  - r-rcppannoy
  - r-rcpparmadillo
  - r-rcppdist
  - r-rcppeigen
  - r-rcpphnsw
  - r-rcppparallel
  - r-rcppprogress
  - r-rcpptoml
  - r-rcurl
  - r-registry
  - r-rematch2
  - r-remotes
  - r-reshape
  - r-reshape2
  - r-restfulr
  - r-reticulate
  - r-rex
  - r-rgeos
  - r-rjags
  - r-rjson
  - r-rlang
  - r-r.methodss3
  - r-rmpi
  - r-rngtools
  - r-rocr
  - r-r.oo
  - r-roxygen2
  - r-rpart
  - r-rprojroot
  - r-rspectra
  - r-rsqlite
  - r-rstudioapi
  - r-rsvd
  - r-rtsne
  - r-rttf2pt1
  - r-r.utils
  - r-rversions
  - r-sandwich
  - r-sass
  - r-scales
  - r-scattermore
  - r-sctransform
  - r-sessioninfo
  - r-seurat
  - r-seuratobject
  - r-shiny
  - r-sitmo
  - r-snow
  - r-sourcetools
  - r-sp
  - r-spatstat
  - r-spatstat.core
  - r-spatstat.data
  - r-spatstat.geom
  - r-spatstat.linnet
  - r-spatstat.random
  - r-spatstat.sparse
  - r-spatstat.utils
  - r-statmod
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-systemfonts
  - r-tensor
  - r-testthat
  - r-textshaping
  - r-th.data
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-usethis
  - r-utf8
  - r-uwot
  - r-vctrs
  - r-vgam
  - r-vipor
  - r-viridis
  - r-viridislite
  - r-waldo
  - r-whisker
  - r-withr
  - r-xfun
  - r-xgboost
  - r-xml
  - r-xml2
  - r-xopen
  - r-xtable
  - r-yaml
  - r-zip
  - r-zoo
