name: sttkit
channels:
  - conda-forge
  - bioconda
dependencies:
  - python == 3.12  
  - bioconda::bioconductor-annotationdbi
  - bioconda::bioconductor-batchelor
  - bioconda::bioconductor-bayesspace
  - bioconda::bioconductor-beachmat
  - bioconda::bioconductor-biobase
  - bioconda::bioconductor-biocfilecache
  - bioconda::bioconductor-biocgenerics
  - bioconda::bioconductor-biocio
  - bioconda::bioconductor-biocneighbors
  - bioconda::bioconductor-biocparallel
  - bioconda::bioconductor-biocsingular
  - bioconda::bioconductor-biomart
  - bioconda::bioconductor-biostrings
  - bioconda::bioconductor-bluster
  - bioconda::bioconductor-bsgenome
  - bioconda::bioconductor-complexheatmap
  - bioconda::bioconductor-delayedarray
  - bioconda::bioconductor-delayedmatrixstats
  - bioconda::bioconductor-dnacopy
  - bioconda::bioconductor-edger
  - bioconda::bioconductor-enhancedvolcano
  - bioconda::bioconductor-genomeinfodb
  - bioconda::bioconductor-genomeinfodbdata
  - bioconda::bioconductor-genomicalignments
  - bioconda::bioconductor-genomicfeatures
  - bioconda::bioconductor-genomicranges
  - bioconda::bioconductor-glmgampoi
  - bioconda::bioconductor-infercnv
  - bioconda::bioconductor-iranges
  - bioconda::bioconductor-keggrest
  - bioconda::bioconductor-limma
  - bioconda::bioconductor-matrixgenerics
  - bioconda::bioconductor-metapod
  - bioconda::bioconductor-residualmatrix
  - bioconda::bioconductor-rhdf5
  - bioconda::bioconductor-rhdf5filters
  - bioconda::bioconductor-rhdf5lib
  - bioconda::bioconductor-rhtslib
  - bioconda::bioconductor-rsamtools
  - bioconda::bioconductor-rtracklayer
  - bioconda::bioconductor-s4vectors
  - bioconda::bioconductor-scaledmatrix
  - bioconda::bioconductor-scater
  - bioconda::bioconductor-scran
  - bioconda::bioconductor-scuttle
  - bioconda::bioconductor-singlecellexperiment
  - bioconda::bioconductor-sparsematrixstats
  - bioconda::bioconductor-summarizedexperiment
  - bioconda::bioconductor-variantannotation
  - bioconda::bioconductor-xvector
  - bioconda::bioconductor-zlibbioc
  - bioconda::r-anndata
  - bioconda::r-restfulr
  - bioconda::r-sceasy
  - conda-forge::r-abind
  - conda-forge::r-ape
  - conda-forge::r-argparse
  - conda-forge::r-ash
  - conda-forge::r-askpass
  - conda-forge::r-assertthat
  - conda-forge::r-backports
  - conda-forge::r-base>=4.3
  - conda-forge::r-base64enc
  - conda-forge::r-beeswarm
  - conda-forge::r-bh
  - conda-forge::r-bibtex
  - conda-forge::r-biocmanager
  - conda-forge::r-bit
  - conda-forge::r-bit64
  - conda-forge::r-bitops
  - conda-forge::r-blob
  - conda-forge::r-brew
  - conda-forge::r-brio
  - conda-forge::r-bslib
  - conda-forge::r-cachem
  - conda-forge::r-cairo
  - conda-forge::r-callr
  - conda-forge::r-catools
  - conda-forge::r-cli
  - conda-forge::r-clipr
  - conda-forge::r-cluster
  - conda-forge::r-coda
  - conda-forge::r-codetools
  - conda-forge::r-coin
  - conda-forge::r-colorspace
  - conda-forge::r-commonmark
  - conda-forge::r-compquadform
  - conda-forge::r-corrplot
  - conda-forge::r-covr
  - conda-forge::r-cowplot
  - conda-forge::r-cpp11
  - conda-forge::r-crayon
  - conda-forge::r-credentials
  - conda-forge::r-crosstalk
  - conda-forge::r-curl
  - conda-forge::r-data.table
  - conda-forge::r-dbi
  - conda-forge::r-dbplyr
  - conda-forge::r-dbscan
  - conda-forge::r-deldir
  - conda-forge::r-desc
  - conda-forge::r-devtools
  - conda-forge::r-dichromat
  - conda-forge::r-diffobj
  - conda-forge::r-digest
  - conda-forge::r-dirichletreg
  - conda-forge::r-doparallel
  - conda-forge::r-dplyr
  - conda-forge::r-dqrng
  - conda-forge::r-dt
  - conda-forge::r-ellipsis
  - conda-forge::r-evaluate
  - conda-forge::r-extrafont
  - conda-forge::r-extrafontdb
  - conda-forge::r-fansi
  - conda-forge::r-farver
  - conda-forge::r-fastcluster
  - conda-forge::r-fastmap
  - conda-forge::r-fields
  - conda-forge::r-filelock
  - conda-forge::r-findpython
  - conda-forge::r-fitdistrplus
  - conda-forge::r-fnn
  - conda-forge::r-fontawesome
  - conda-forge::r-foreach
  - conda-forge::r-formatr
  - conda-forge::r-formula
  - conda-forge::r-fs
  - conda-forge::r-futile.logger
  - conda-forge::r-futile.options
  - conda-forge::r-future
  - conda-forge::r-future.apply
  - conda-forge::r-generics
  - conda-forge::r-gert
  - conda-forge::r-getopt
  - conda-forge::r-ggalt
  - conda-forge::r-ggbeeswarm
  - conda-forge::r-ggforce
  - conda-forge::r-ggplot2
  - conda-forge::r-ggpmisc
  - conda-forge::r-ggraph
  - conda-forge::r-ggrastr
  - conda-forge::r-ggrepel
  - conda-forge::r-ggridges
  - conda-forge::r-gh
  - conda-forge::r-git2r
  - conda-forge::r-gitcreds
  - conda-forge::r-globals
  - conda-forge::r-glue
  - conda-forge::r-goftest
  - conda-forge::r-gplots
  - conda-forge::r-gridbase
  - conda-forge::r-gridextra
  - conda-forge::r-gtable
  - conda-forge::r-gtools
  - conda-forge::r-harmony
  - conda-forge::r-hdf5r
  - conda-forge::r-here
  - conda-forge::r-hexbin
  - conda-forge::r-hiddenmarkov
  - conda-forge::r-highr
  - conda-forge::r-hms
  - conda-forge::r-htmltools
  - conda-forge::r-htmlwidgets
  - conda-forge::r-httpuv
  - conda-forge::r-httr
  - conda-forge::r-ica
  - conda-forge::r-igraph
  - conda-forge::r-ini
  - conda-forge::r-irlba
  - conda-forge::r-isoband
  - conda-forge::r-iterators
  - conda-forge::r-jquerylib
  - conda-forge::r-jsonlite
  - conda-forge::r-kernsmooth
  - conda-forge::r-knitr
  - conda-forge::r-labeling
  - conda-forge::r-lambda.r
  - conda-forge::r-later
  - conda-forge::r-lattice
  - conda-forge::r-lazyeval
  - conda-forge::r-leiden
  - conda-forge::r-libcoin
  - conda-forge::r-lifecycle
  - conda-forge::r-listenv
  - conda-forge::r-lmtest
  - conda-forge::r-locfdr
  - conda-forge::r-locfit
  - conda-forge::r-lsei
  - conda-forge::r-lwgeom
  - conda-forge::r-magick
  - conda-forge::r-magrittr
  - conda-forge::r-maps
  - conda-forge::r-markdown
  - conda-forge::r-mass
  - conda-forge::r-mathjaxr
  - conda-forge::r-matrix
  - conda-forge::r-matrixstats
  - conda-forge::r-maxlik
  - conda-forge::r-mclust
  - conda-forge::r-memoise
  - conda-forge::r-metadat
  - conda-forge::r-metafor
  - conda-forge::r-mgcv
  - conda-forge::r-mime
  - conda-forge::r-miniui
  - conda-forge::r-misctools
  - conda-forge::r-modeltools
  - conda-forge::r-multcomp
  - conda-forge::r-munsell
  - conda-forge::r-mvtnorm
  - conda-forge::r-nlme
  - conda-forge::r-nmf
  - conda-forge::r-npsurv
  - conda-forge::r-openssl
  - conda-forge::r-openxlsx
  - conda-forge::r-optparse
  - conda-forge::r-pals
  - conda-forge::r-parallelly
  - conda-forge::r-patchwork
  - conda-forge::r-pbapply
  - conda-forge::r-pheatmap
  - conda-forge::r-phyclust
  - conda-forge::r-pillar
  - conda-forge::r-pkgbuild
  - conda-forge::r-pkgconfig
  - conda-forge::r-pkgload
  - conda-forge::r-pkgmaker
  - conda-forge::r-plogr
  - conda-forge::r-plotly
  - conda-forge::r-plyr
  - conda-forge::r-png
  - conda-forge::r-polyclip
  - conda-forge::r-praise
  - conda-forge::r-prettyunits
  - conda-forge::r-processx
  - conda-forge::r-progress
  - conda-forge::r-progressr
  - conda-forge::r-proj4
  - conda-forge::r-promises
  - conda-forge::r-ps
  - conda-forge::r-purrr
  - conda-forge::r-quadprog
  - conda-forge::r-r6
  - conda-forge::r-ragg
  - conda-forge::r-randomforestsrc
  - conda-forge::r-rann
  - conda-forge::r-rappdirs
  - conda-forge::r-rcmdcheck
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-rcpp
  - conda-forge::r-rcppannoy
  - conda-forge::r-rcpparmadillo
  - conda-forge::r-rcppdist
  - conda-forge::r-rcppeigen
  - conda-forge::r-rcppgsl
  - conda-forge::r-rcpphnsw
  - conda-forge::r-rcppparallel
  - conda-forge::r-rcppprogress
  - conda-forge::r-rcpptoml
  - conda-forge::r-rcppziggurat
  - conda-forge::r-rcurl
  - conda-forge::r-registry
  - conda-forge::r-rematch2
  - conda-forge::r-remotes
  - conda-forge::r-reshape
  - conda-forge::r-reshape2
  - conda-forge::r-reticulate
  - conda-forge::r-rex
  - conda-forge::r-rgeos
  - conda-forge::r-rjags
  - conda-forge::r-rjson
  - conda-forge::r-rlang
  - conda-forge::r-r.methodss3
  - conda-forge::r-rmpi
  - conda-forge::r-rngtools
  - conda-forge::r-rocr
  - conda-forge::r-r.oo
  - conda-forge::r-roxygen2
  - conda-forge::r-rpart
  - conda-forge::r-rprojroot
  - conda-forge::r-rspectra
  - conda-forge::r-rsqlite
  - conda-forge::r-rstudioapi
  - conda-forge::r-rsvd
  - conda-forge::r-rtsne
  - conda-forge::r-rttf2pt1
  - conda-forge::r-r.utils
  - conda-forge::r-rversions
  - conda-forge::r-sandwich
  - conda-forge::r-sass
  - conda-forge::r-scales
  - conda-forge::r-scattermore
  - conda-forge::r-scatterpie
  - conda-forge::r-sctransform
  - conda-forge::r-sessioninfo
  - conda-forge::r-seurat
  - conda-forge::r-seuratobject
  - conda-forge::r-shiny
  - conda-forge::r-sitmo
  - conda-forge::r-snow
  - conda-forge::r-sourcetools
  - conda-forge::r-sp
  - conda-forge::r-spam
  - conda-forge::r-spatial
  - conda-forge::r-spatstat
  - conda-forge::r-spatstat.core
  - conda-forge::r-spatstat.data
  - conda-forge::r-spatstat.geom
  - conda-forge::r-spatstat.linnet
  - conda-forge::r-spatstat.random
  - conda-forge::r-spatstat.sparse
  - conda-forge::r-spatstat.utils
  - conda-forge::r-statmod
  - conda-forge::r-stringi
  - conda-forge::r-stringr
  - conda-forge::r-survival
  - conda-forge::r-sys
  - conda-forge::r-systemfonts
  - conda-forge::r-tensor
  - conda-forge::r-terra
  - conda-forge::r-testthat
  - conda-forge::r-textshaping
  - conda-forge::r-th.data
  - conda-forge::r-tibble
  - conda-forge::r-tidyr
  - conda-forge::r-tidyselect
  - conda-forge::r-usethis
  - conda-forge::r-utf8
  - conda-forge::r-uwot
  - conda-forge::r-vctrs
  - conda-forge::r-vgam
  - conda-forge::r-vipor
  - conda-forge::r-viridis
  - conda-forge::r-viridislite
  - conda-forge::r-waldo
  - conda-forge::r-whisker
  - conda-forge::r-withr
  - conda-forge::r-xfun
  - conda-forge::r-xgboost
  - conda-forge::r-xml
  - conda-forge::r-xml2
  - conda-forge::r-xopen
  - conda-forge::r-xtable
  - conda-forge::r-yaml
  - conda-forge::r-zip
  - conda-forge::r-zoo
